### ISSUE TITLE
Writing metadata dynamically causes PdfParseError

### ISSUE THREAD

**Issue by SimonLammer** [pmaupin/pdfrw#135]
```
>>> import pdfrw
>>> r = pdfrw.PdfReader('my.pdf')
>>> r.Info
{'/CreationDate': "(D:20160516000000+02'00')", '/ModDate': "(D:20180607212708+02'00')", '/Title': '(MyPdf)'}
>>> key = '/foo'
>>> r.Info[key] = 'bar'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\pdfrw\objects\pdfdict.py", line 108, in __setitem__
    raise PdfParseError('Dict key %s is not a PdfName' % repr(name))
pdfrw.errors.PdfParseError: Dict key '/foo' is not a PdfName
>>> r.Info.foo = 'bar'
>>> r.Info
{'/CreationDate': "(D:20160516000000+02'00')", '/ModDate': "(D:20180607212708+02'00')", '/Title': '(Pkw Mehrphasen Training)', '/foo': 'bar'}
```

1. Why am I getting an error on `r.Info[key] = 'bar'`?
2. Is there a workaround?

*Edit 1*: r.Info.update seems to work, but throws an error on writing - resulting in an empty pdf file
```
...
>>> r.Info
{'/CreationDate': "(D:20160516000000+02'00')", '/ModDate': "(D:20180607212708+02'00')", '/Title': '(MyPdf)'}
>>> r.Info.update({'/foo': 'bar'})
>>> r.Info
{'/CreationDate': "(D:20160516000000+02'00')", '/ModDate': "(D:20180607212708+02'00')", '/Title': '(MyPdf)', '/foo': 'bar'}
>>> w = pdfrw.PdfWriter('my.pdf', trailer=r)
>>> w.write()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\pdfrw\pdfwriter.py", line 358, in write
    self.killobj, user_fmt=user_fmt)
  File "C:\Program Files\Python36\lib\site-packages\pdfrw\pdfwriter.py", line 196, in FormatObjects
    format_deferred()
  File "C:\Program Files\Python36\lib\site-packages\pdfrw\pdfwriter.py", line 164, in format_deferred
    objlist[index] = format_obj(obj)
  File "C:\Program Files\Python36\lib\site-packages\pdfrw\pdfwriter.py", line 141, in format_obj
    for (x, y) in obj.iteritems())
  File "C:\Program Files\Python36\lib\site-packages\pdfrw\pdfwriter.py", line 140, in <genexpr>
    pairs = sorted((getattr(x, 'encoded', None) or x, y)
  File "C:\Program Files\Python36\lib\site-packages\pdfrw\objects\pdfdict.py", line 179, in iteritems
    repr(key))
pdfrw.errors.PdfParseError: Dict key '/foo' is not a PdfName
>>> r2 = pdfrw.PdfReader('my.pdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\pdfrw\pdfreader.py", line 585, in __init__
    raise PdfParseError('Empty PDF file!')
pdfrw.errors.PdfParseError: Empty PDF file!
```

**Comment by SimonLammer** [comment]
As a workaround, I can convert the key to a PdfName myself `r.Info.foo = 'bar'`:
```
>>> r.Info[pdfrw.objects.pdfname.BasePdfName('/foo')] = 'bar'
>>> w = PdfWriter('my.pdf')
>>> w = PdfWriter('my.pdf', trailer=r)
>>> w.write()
>>> r2 = PdfReader('my.pdf')
>>> r2.Info
{'/CreationDate': "(D:20160722000000+02'00')", '/ModDate': "(D:20180607212711+02'00')", '/Title': '(MyPdf)', '/foo': '(bar)'}
```

I expected this to be handled automatically, as it is when using `r.Info.foo = 'bar'`.

**Comment by pmaupin** [comment]
Try `key = PdfName('foo')`

**Comment by pmaupin** [comment]
I think using '/foo' might be supported by fixes in git (maybe even already released?), but it's not that usual to use dynamic keys for PDF dictionaries, which is why the problem went unnoticed for awhile.
