### ISSUE TITLE
Cannot use deepcopy on pdfrw.objects.pdfdict.PdfDict

### ISSUE THREAD

**Issue by bwolleb** [pmaupin/pdfrw#141]
Hi,
I need to copy a PdfDict using depcopy with the following code:

```python
from copy import deepcopy
from pdfrw import PdfReader
from pdfrw.buildxobj import pagexobj

pages = PdfReader("test.pdf").pages
xobj = pagexobj(pages[0])
copiedxobj = deepcopy(xobj)
```

and I get the following exception:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    copiedxobj = deepcopy(xobj)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: 'NoneType' object is not callable
```
Do you have any idea how it could be fixed?

**Comment by sunlinkun** [comment]
I have encountered the same problem. Do you know how to solve it?

**Comment by bwolleb** [comment]
Wow, so much time has passed that I don't even remember how I worked around it. I think I read the file in a buffer and then pass the buffer to the PdfReader class instead of a string, in order to avoid accessing the disk for every reader.

**Comment by sunlinkun** [comment]
> Wow, so much time has passed that I don't even remember how I worked around it. I think I read the file in a buffer and then pass the buffer to the PdfReader class instead of a string, in order to avoid accessing the disk for every reader.

Thanks! This is a new approach for me. I will try it.
